// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDisEIJx5fmlmJ2NBOT6q7aG_Wqwzu7uLk',
    appId: '1:461308356175:ios:4c60a109a23f3723872c3a',
    messagingSenderId: '461308356175',
    projectId: 'gemini-powered-flutter-app',
    storageBucket: 'gemini-powered-flutter-app.firebasestorage.app',
    iosBundleId: 'com.example.colorist',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAS4GOUeoBlAp6ZUA0cvGpgbAmGkQ6WX3I',
    appId: '1:461308356175:web:8f08c7cf29f7e2dd872c3a',
    messagingSenderId: '461308356175',
    projectId: 'gemini-powered-flutter-app',
    authDomain: 'gemini-powered-flutter-app.firebaseapp.com',
    storageBucket: 'gemini-powered-flutter-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDisEIJx5fmlmJ2NBOT6q7aG_Wqwzu7uLk',
    appId: '1:461308356175:ios:4c60a109a23f3723872c3a',
    messagingSenderId: '461308356175',
    projectId: 'gemini-powered-flutter-app',
    storageBucket: 'gemini-powered-flutter-app.firebasestorage.app',
    iosBundleId: 'com.example.colorist',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqM-bwfmfrWZMGYrte31r49I84f95zfzI',
    appId: '1:461308356175:android:2e9ef0ba38c2e517872c3a',
    messagingSenderId: '461308356175',
    projectId: 'gemini-powered-flutter-app',
    storageBucket: 'gemini-powered-flutter-app.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAS4GOUeoBlAp6ZUA0cvGpgbAmGkQ6WX3I',
    appId: '1:461308356175:web:40917ef4b6cbe0c2872c3a',
    messagingSenderId: '461308356175',
    projectId: 'gemini-powered-flutter-app',
    authDomain: 'gemini-powered-flutter-app.firebaseapp.com',
    storageBucket: 'gemini-powered-flutter-app.firebasestorage.app',
  );
}
